import type { ParentInstitution, EducationalService, EducationPlan } from "@/types/tenant"

export const mockParentInstitutions: ParentInstitution[] = [
    { id: 1, name: "State University System", slug: "state-university", type: "UNIVERSITY" },
    { id: 2, name: "Regional Education Board", slug: "regional-board", type: "INSTITUTE" },
    { id: 3, name: "Metropolitan School District", slug: "metro-district", type: "SCHOOL" },
]

export const availableFeatures = [
    "Student Information System",
    "Learning Management System",
    "Grade Management",
    "Attendance Tracking",
    "Fee Management",
    "Library Management",
    "Examination System",
    "Timetable Management",
    "Parent Portal",
    "Mobile App Access",
    "Online Admissions",
    "Certificate Generation",
    "Alumni Management",
    "Hostel Management",
    "Transport Management",
    "Inventory Management",
    "HR & Payroll",
    "Financial Accounting",
]

export const educationalServices: EducationalService[] = [
    {
        id: 1,
        name: "Advanced Analytics Dashboard",
        description: "Comprehensive analytics for student performance and institutional insights",
        price: 99.99,
        billingCycle: "MONTHLY",
        category: "Analytics",
        isActive: true,
    },
    {
        id: 2,
        name: "24/7 Technical Support",
        description: "Round-the-clock technical support for your institution",
        price: 299.99,
        billingCycle: "MONTHLY",
        category: "Support",
        isActive: true,
    },
    {
        id: 3,
        name: "Additional Storage (1TB)",
        description: "Extra cloud storage for documents, videos, and course materials",
        price: 49.99,
        billingCycle: "MONTHLY",
        category: "Storage",
        isActive: true,
    },
    {
        id: 4,
        name: "API Integration Suite",
        description: "Advanced API access for third-party integrations",
        price: 149.99,
        billingCycle: "MONTHLY",
        category: "Integration",
        isActive: true,
    },
    {
        id: 5,
        name: "White Label Solution",
        description: "Complete branding customization with your institution's identity",
        price: 999.99,
        billingCycle: "YEARLY",
        category: "Branding",
        isActive: true,
    },
    {
        id: 6,
        name: "Advanced Security Package",
        description: "Enhanced security with SSO, 2FA, and audit logs",
        price: 199.99,
        billingCycle: "MONTHLY",
        category: "Security",
        isActive: true,
    },
    {
        id: 7,
        name: "Online Proctoring System",
        description: "AI-powered online examination proctoring solution",
        price: 399.99,
        billingCycle: "MONTHLY",
        category: "Examination",
        isActive: true,
    },
    {
        id: 8,
        name: "Virtual Classroom Pro",
        description: "Advanced virtual classroom with recording and breakout rooms",
        price: 249.99,
        billingCycle: "MONTHLY",
        category: "Learning",
        isActive: true,
    },
]

export const educationPlans: EducationPlan[] = [
    {
        id: 1,
        planName: "Starter",
        planType: "BASIC",
        billingCycle: "MONTHLY",
        price: 199.99,
        status: "ACTIVE",
        startDate: "2024-01-01",
        autoRenew: true,
        maxStudents: 500,
        maxFaculty: 50,
        features: [
            "Student Information System",
            "Basic Grade Management",
            "Attendance Tracking",
            "Parent Portal",
            "Email Support",
        ],
    },
    {
        id: 2,
        planName: "Standard",
        planType: "STANDARD",
        billingCycle: "MONTHLY",
        price: 499.99,
        status: "ACTIVE",
        startDate: "2024-01-01",
        autoRenew: true,
        popular: true,
        maxStudents: 2000,
        maxFaculty: 200,
        features: [
            "Complete SIS",
            "Learning Management System",
            "Advanced Grade Management",
            "Fee Management",
            "Library Management",
            "Mobile App Access",
            "Priority Support",
        ],
    },
    {
        id: 3,
        planName: "Premium",
        planType: "PREMIUM",
        billingCycle: "MONTHLY",
        price: 999.99,
        status: "ACTIVE",
        startDate: "2024-01-01",
        autoRenew: true,
        maxStudents: 5000,
        maxFaculty: 500,
        features: [
            "Full ERP Suite",
            "Advanced Analytics",
            "Examination System",
            "HR & Payroll",
            "Financial Accounting",
            "Custom Integrations",
            "24/7 Support",
        ],
    },
    {
        id: 4,
        planName: "Enterprise",
        planType: "ENTERPRISE",
        billingCycle: "MONTHLY",
        price: 1999.99,
        status: "ACTIVE",
        startDate: "2024-01-01",
        autoRenew: true,
        maxStudents: 999999,
        maxFaculty: 999999,
        features: [
            "Unlimited Everything",
            "Multi-Campus Support",
            "Advanced Security",
            "Custom Development",
            "Dedicated Support Team",
            "On-premise Deployment",
            "White Label Solution",
        ],
    },
]

export const timezones = [
    { value: "UTC", label: "UTC" },
    { value: "America/New_York", label: "Eastern Time (ET)" },
    { value: "America/Chicago", label: "Central Time (CT)" },
    { value: "America/Denver", label: "Mountain Time (MT)" },
    { value: "America/Los_Angeles", label: "Pacific Time (PT)" },
    { value: "Europe/London", label: "London (GMT)" },
    { value: "Europe/Paris", label: "Paris (CET)" },
    { value: "Asia/Tokyo", label: "Tokyo (JST)" },
    { value: "Asia/Kolkata", label: "India (IST)" },
    { value: "Australia/Sydney", label: "Sydney (AEST)" },
]

export const currencies = [
    { value: "USD", label: "USD - US Dollar" },
    { value: "EUR", label: "EUR - Euro" },
    { value: "GBP", label: "GBP - British Pound" },
    { value: "INR", label: "INR - Indian Rupee" },
    { value: "CAD", label: "CAD - Canadian Dollar" },
    { value: "AUD", label: "AUD - Australian Dollar" },
]

export const languages = [
    { value: "en", label: "English" },
    { value: "es", label: "Spanish" },
    { value: "fr", label: "French" },
    { value: "de", label: "German" },
    { value: "hi", label: "Hindi" },
    { value: "zh", label: "Chinese" },
]

export const academicYears = [
    { value: "2024-25", label: "2024-25" },
    { value: "2025-26", label: "2025-26" },
    { value: "2026-27", label: "2026-27" },
]

